### ISSUE TITLE
Quilt+ MVP-1: Download package URI inside root folder

### ISSUE THREAD

**Issue by drernie** [quiltdata/quiltplus#2]
As a client calling the Quilt+ API,
I want to be able to create a package Resource from a URI
So that I can download it inside a pre-defined Root folder

**Comment by drernie** [comment]
Verify if `fondat` the right framework to use for this
https://github.com/fondat/fondat

**Comment by drernie** [comment]
# MVP-1a: URI Resource

Using the proposed [YAML format](https://github.com/fondat/fondat/issues/3): 

How to represent, say: 
`quilt+s3://quilt-example#package=examples/wellplates@fb5f3dc1b814246548dfe1492c8d00309a36e00c65b4774cbae97c5addb6359c&path=README.md`

```
QuiltPlusURI:
  *registry: "s3://quilt-example"# mandatory
  package: examples/wellplates
  top_hash: fb5f3dc1b814246548dfe1492c8d00309a36e00c65b4774cbae97c5addb6359c
  path: README.md. 
  catalog: "https://open.quiltdata.com"
  property: "size=363"
```
Implying a schema of:

```
cls_name:
  registry: 
    type: uri
    optional: false
  package: str # require "/"
  top_hash: base64
  path: str 
  catalog: url
  property: json
```

It should be possible to GET the Package Resource from a URI Resource:

```
package:
  prefix:  examples
  suffix: wellplates
  top_hash: fb5f3dc1b814246548dfe1492c8d00309a36e00c65b4774cbae97c5addb6359c
```

Then GET to install it (and perhaps LIST to retrieve all the Path Resources)
